import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  pageContainer: { padding: 16, backgroundColor: '#fff', paddingBottom: 40 },
  logoTop: { width: '100%', borderRadius: 8, overflow: 'hidden', marginBottom: 10 },
  logo: { width: "100%", height: 200, resizeMode: 'stretch' },
  pageTitle: { fontSize: 22, fontWeight: '700', textAlign: 'center', marginVertical: 8 },
  infoPorcao: { textAlign: 'center', color: '#555', marginBottom: 12 },
  card: { backgroundColor: '#fff', borderRadius: 10, padding: 12, marginBottom: 10, elevation: 1 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  name: { fontWeight: '700', fontSize: 16 },
  subtotal: { color: '#333', fontWeight: '700' },
  tipoQtd: { alignItems: 'flex-start' },
  tipoBlock: { flex: 1 },
  qtdBlock: { alignItems: 'flex-end' },
  label: { fontWeight: '600', marginBottom: 6 },
  pillsRow: { flexDirection: 'row', marginTop: 6 },
  pill: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 20, backgroundColor: '#f5f5f5', borderWidth: 1, borderColor: '#ddd', marginRight: 8 },
  pillSelected: { backgroundColor: '#22a55f', borderColor: '#22a55f' },
  pillText: { color: '#333' },
  pillSelectedText: { color: '#fff', fontWeight: '700' },
  qtdButtons: { flexDirection: 'row', alignItems: 'center' },
  qbtn: { padding: 8, borderRadius: 6, borderWidth: 1, borderColor: '#ccc', backgroundColor: '#fff' },
  qbtnText: { fontSize: 16, fontWeight: '700' },
  qtext: { minWidth: 36, textAlign: 'center', marginHorizontal: 8 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 12, marginBottom: 8 },
  totalLabel: { fontWeight: '700' },
  totalValue: { fontSize: 18, fontWeight: '800', color: '#22a55f' },
  primaryBtn: { width: '100%', backgroundColor: '#22a55f', padding: 14, borderRadius: 10, marginTop: 8, alignItems: 'center' },
  primaryBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  input: { backgroundColor: '#f5f5f5', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', marginBottom: 12 },
  pickerFake: { padding: 12, borderWidth: 1, borderColor: '#ddd', borderRadius: 8, backgroundColor: '#fff' },
  modalBg: { flex:1, justifyContent:'center', alignItems:'center', backgroundColor:'rgba(0,0,0,0.3)' },
  modalContainer: { backgroundColor:'#fff', borderRadius:8, width:'80%', maxHeight:'60%' },
  modalItem: { padding:12, borderBottomWidth:1, borderBottomColor:'#eee' },
  paymentButtons: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 8 },
  totalBox: { marginVertical: 12, paddingVertical: 8 },
  totalText: { fontSize: 18, fontWeight: '700', color: 'green' },
});
