name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build Expo Web
        run: npx expo export --platform web

      # Ajuste do base path para o nome EXATO do repositório: Projetoextens-o
      - name: Patch base path for GitHub Pages
        run: |
            sed -i 's|href="/|href="/projetoextens-o/|g' web-build/index.html || true
            sed -i 's|src="/|src="/projetoextens-o/|g'  web-build/index.html || true
            sed -i 's|<head>|<head><base href="/projetoextens-o/">|g' web-build/index.html || true

            find web-build -type f -name "*.js" -print0 | xargs -0 sed -i \
            -e 's|"/_expo/|"/projetoextens-o/_expo/|g' \
            -e 's|"/assets/|"/projetoextens-o/assets/|g'

            if [ -f web-build/metadata.json ]; then
            sed -i 's|"/assets/|"/projetoextens-o/assets/|g' web-build/metadata.json || true
            fi

            find web-build -type f -name "*.css" -print0 | xargs -0 sed -i \
            -e "s|url('/assets/|url('/projetoextens-o/assets/|g" \
            -e 's|url("/assets/|url("/projetoextens-o/assets/|g'

      # SPA fallback (evita 404 em navegação client-side)
      - name: Copy 404.html for SPA fallback
        run: cp web-build/index.html web-build/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: web-build
